apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cosy-postgresql
spec:
  project: cosy
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 12.17.0
    helm:
      releaseName: cosy-postgresql
      values: |
        global:
          storageClass: "standard" 
        auth:
          existingSecret: cosy-postgresql-credentials
          existingSecretUsernameKey: postgresql-username
          existingSecretPasswordKey: postgresql-password
          database: cosy
        primary:
          persistence:
            enabled: true
            size: 5Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: cosy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
