apiVersion: v1
kind: Service
metadata:
  name: cosy-postgres
  namespace: cosy
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: cosy-postgres
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cosy-postgres-pvc
  namespace: cosy
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cosy-postgres
  namespace: cosy
spec:
  serviceName: "cosy-postgres"
  replicas: 1
  selector:
    matchLabels:
      app: cosy-postgres
  template:
    metadata:
      labels:
        app: cosy-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16
        ports:
        - containerPort: 5432
        
        # Map the Official Image Env Vars to your Secret Keys
        env:
        - name: POSTGRES_DB
          value: "cosydb"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: cosy-postgresql-credentials
              key: postgresql-username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cosy-postgresql-credentials
              key: postgresql-password
              
        # Mount the volume
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
          
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: cosy-postgres-pvc
